// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGYbsK3G6Udukar3D8BnaSoEpER8jEen0',
    appId: '1:172323605183:web:b8b591a2dbde709f8b940a',
    messagingSenderId: '172323605183',
    projectId: 'religious-qa-app-2026-a4aed',
    authDomain: 'religious-qa-app-2026-a4aed.firebaseapp.com',
    storageBucket: 'religious-qa-app-2026-a4aed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHJKyL7eNWrxyvFJO9DNPUS2paOX-e5Bc',
    appId: '1:172323605183:android:8f801bb0faa0ac1c8b940a',
    messagingSenderId: '172323605183',
    projectId: 'religious-qa-app-2026-a4aed',
    storageBucket: 'religious-qa-app-2026-a4aed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKAjxfrK5tE4XtGD1EgGCRfbtuKFQEWk',
    appId: '1:172323605183:ios:86518a3d1e7bc8ad8b940a',
    messagingSenderId: '172323605183',
    projectId: 'religious-qa-app-2026-a4aed',
    storageBucket: 'religious-qa-app-2026-a4aed.firebasestorage.app',
    androidClientId: '172323605183-bhjfgg24do35us51t9l71nl0rqg88l30.apps.googleusercontent.com',
    iosClientId: '172323605183-5e898vhp9mg9pibuqodeggqblqn58tii.apps.googleusercontent.com',
    iosBundleId: 'com.abdulrahman.tasbeeh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKAjxfrK5tE4XtGD1EgGCRfbtuKFQEWk',
    appId: '1:172323605183:ios:151f2c06c9339c8f8b940a',
    messagingSenderId: '172323605183',
    projectId: 'religious-qa-app-2026-a4aed',
    storageBucket: 'religious-qa-app-2026-a4aed.firebasestorage.app',
    androidClientId: '172323605183-bhjfgg24do35us51t9l71nl0rqg88l30.apps.googleusercontent.com',
    iosClientId: '172323605183-bci8ti3b06rdpeq35hcfosmg0sf5rti4.apps.googleusercontent.com',
    iosBundleId: 'com.example.religiousQaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGYbsK3G6Udukar3D8BnaSoEpER8jEen0',
    appId: '1:172323605183:web:d02ddfd0660783448b940a',
    messagingSenderId: '172323605183',
    projectId: 'religious-qa-app-2026-a4aed',
    authDomain: 'religious-qa-app-2026-a4aed.firebaseapp.com',
    storageBucket: 'religious-qa-app-2026-a4aed.firebasestorage.app',
  );

}